# Generated by Django 5.0 on 2023-12-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_notification_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='created',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='modified',
        ),
        migrations.AddField(
            model_name='notification',
            name='send_time_notif',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
